workflows:
  astrocam_release:
    name: AstroCam Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "AstroCam.xcodeproj"
        XCODE_SCHEME: "AstroCam"
        BUNDLE_ID: "com.giuseppe.astrocam"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Show Xcode version
        script: |
          xcodebuild -version
          xcode-select -p

      - name: List schemes
        script: |
          xcodebuild -list -project "$XCODE_PROJECT"

      - name: Clean
        script: |
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release

      - name: Build (no signing)
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive (requires signing later)
        script: |
          mkdir -p build
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/AstroCam.xcarchive

      - name: Export IPA (will work after signing is configured in Codemagic)
        script: |
          # ExportOptions.plist minimale (da adattare quando scegliamo ad-hoc o app-store)
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/AstroCam.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/export/*.ipa
      - build/AstroCam.xcarchive/**/*
      - $HOME/Library/Logs/DiagnosticReports/**/*
      - /tmp/xcodebuild*.log
